echo [信息] 下载ishop-dependencies....
git clone https://github.com/menyin/ishop-dependencies.git
echo [信息] 下载ishop-commons....
git clone https://github.com/menyin/ishop-commons.git
echo [信息] 下载ishop-commons-domain....
git clone https://github.com/menyin/ishop-commons-domain.git
echo [信息] 下载ishop-commons-mapper....
git clone https://github.com/menyin/ishop-commons-mapper.git
echo [信息] 下载ishop-commons-service....
git clone https://github.com/menyin/ishop-commons-service.git
echo [信息] 下载ishop-database....
git clone https://github.com/menyin/ishop-database.git
echo [信息] 下载ishop-service-reg....
git clone https://github.com/menyin/ishop-service-reg.git
echo [信息] 下载ishop-service-gateway....
git clone https://github.com/menyin/ishop-service-gateway.git

echo  ....
pause